[profile.default]
# Directory Setup
script = "script"
src = "contracts"
test = "test"

# Gas/Memory
gas_limit = '18446744073709551615' 
memory_limit = 1073741824 # 1 GB

# Compiler Options
bytecode_hash = "none"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.28"
via_ir = false

# Permissions
fs_permissions = [{access = "read-write", path = "./"}]

[rpc_endpoints]
base = "https://base.gateway.tenderly.co"
bsc = "https://bsc-rpc.publicnode.com"
mainnet = "https://mainnet.gateway.tenderly.co"

[etherscan]
base = {key = "${ETHERSCAN_KEY}"}
bsc = {key = "${ETHERSCAN_KEY}"}
mainnet = {key = "${ETHERSCAN_KEY}"}
